chore: 릴리즈 봇 release finish 테스트 (#9)
* chore: yarn install를 install git-flow 뒤로 순서 변경

* chore: git flow release 강제 옵션 추가

* chore: -F 옵션 수정

* chore: install 과정 삭제

* chore: script version을 사용하도록 수정

* build: changelog preset 설치

* chore: yarn install 추가

* chore: yarn install 삭제

* build: conventional-changelog-conventionalcommits 버전 다운

* chore: install 과정 추가

* chore: install 과정 삭제

* chore: changelog preset 삭제 (changelog 테스트를 위함)

* fix: push origin 브랜치 명 수정

* fix: 릴리즈 브랜치 명으로 변경

* fix: release 브랜치 publish 후 push

* chore: chagnelog 생성 후 파싱 추가

* fix: empty commit allow

* fix: CHANGELOG 확인 주석 추가

* fix: 주석 수정

* fix: 주석 수정

* fix; 주석 추가

* fix: 생성된 changelog를 push

* fix: 오타 수정

* fix: env 주석 추가

* fix: lerna version push 로 변경 주석 수정

* fix: current branch 주석

* fix: Changelog print, check

* fix: 추출한 changelog 출력

* fix: changelog 추출 테스트

* fix: changelog 출력 테스트

* fix: changelog preset에 맞춰 추출 명령문 수정

* fix: 주석 삭제 및 메시지 전송 수정

* fix: 릴리즈 브랜치 닫기 주석 처리

* fix: web hook url 변수명 수정

* fix: 슬랙 메시지 형식 수정

* fix: 슬랙 웹훅 변수명 수정

* fix: 메시지 형식 수정

* fix: 메시지 형식 수정

* fix: 메시지 changelog 내용 포함

* feat: release-start 가 끝나면 event 출력

* docs: event 보낸 곳의 inputs 확인

* fix: 완료 버튼 눌렀을 때 release-finish jobs가 돌도록 조건 설정

* docs: dispatch event 확인 주석

* fix: release-finish jobs가 실행되는 조건을 repository_dispatch로 수정

* fix: 실행 조건 추가 및 release-start 조건 설정

* fix: release-finish 조건 수정

* fix:  release-finish 조건을 repository_dispatch 만으로 수정, 주석 추가

* fix: 테스트를 위해 needs 주석

* fix: release finish 추가

* fix: jobs를 하나로 통일

* fix: release-finish 분리, git flow 설치 추가

* fix: checkout 추가

* fix: git flow init 추가

* fix: release-finish 브랜치 최신화

* fix: 릴리즈 브랜치로 checkout

* fix: today_date 추가

* fix: git user info 세팅

* fix: 릴리즈 브랜치 이름 변경, input 추가, types 변경

* fix: 릴리즈 브랜치 이름에서 input 제거

* fix: 태그와 푸시가 되도록 lerna version 명령어 수정

* fix: 릴리즈 브랜치 이름 index 0 추가

* feat: changelog preset 및 version script 수정 (#7)

* fix: slack 메시지 내용 추가 및 수정

* fix: version script no tag, no push 로수정

* feat: changelog preset

* feat: 의존성 설치 step 추가 (#8)

diff --git a/.github/workflows/create-changelog.yml b/.github/workflows/create-changelog.yml
--- a/.github/workflows/create-changelog.yml
+++ b/.github/workflows/create-changelog.yml
@@ -7,6 +7,11 @@ on:
         description: '스프린트 번호'
         required: true
         default: '90'
+      index:
+        description: '릴리즈 브랜치의 index'
+        default: '1'
+  repository_dispatch:
+    types: [릴리즈 완료]
   # schedule:
   #   - cron: "0 9 * * 1"  # 예: 매주 월요일 오전 9시에 실행 (UTC 기준)
   # push:
@@ -14,13 +19,172 @@ on:
   #     - 'release/*'
 
 jobs:
-  release:
+  release-start:
     runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'workflow_dispatch' }}
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      # 브랜치 최신화
+      - name: Update remote branches
+        run: git remote update
+
+      - name: Checkout and update master branch
+        run: |
+          git checkout master
+          git pull origin master
+
+      - name: Checkout and update develop branch
+        run: |
+          git checkout develop
+          git pull origin develop
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '18.20.0'
+
+      - name: Install Dependencies
+        run: yarn install
+
+      - name: Install git flow
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y git-flow
+
+      - name: Get Release branch's name
+        run: |
+          TODAY_DATE=$(node -e 'const today = new Date(); console.log(`${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, "0")}${String(today.getDate()).padStart(2, "0")}`)')
+          echo "RELEASE_BRANCH_NAME=${TODAY_DATE}-0" >> $GITHUB_ENV
+
+      # 릴리즈 브랜치 생성
+      - name: Start Release with git flow and lerna version
+        run: |
+          git flow init -d
+          git flow release start -F ${{ env.RELEASE_BRANCH_NAME }}
+
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+          git commit --allow-empty -m "feat: 정기 릴리즈를 위한 커밋"
+
+          git flow release publish ${{ env.RELEASE_BRANCH_NAME }}
+          yarn run version
+
+      - name: Verify and Download CHANGELOG.md
+        run: |
+          if [ -f "CHANGELOG.md" ]; then
+            echo "CHANGELOG.md found in repository."
+          else
+            echo "CHANGELOG.md not found."
+            exit 1
+          fi
+          cat CHANGELOG.md
+
+      # 이번 스프린트 작업 내역 파싱(릴리즈 노트를 위한 내용)
+      - name: Read the latest minor CHANGELOG entry
+        run: |
+          # 최근 '##' 헤더부터 이전 '##' 헤더까지 내용을 CHANGELOG.md에서 추출
+          CHANGELOG=$(awk '/^## /{if (found) exit; found=1} found{print}' CHANGELOG.md)
+
+          # 마크다운 타이틀을 Slack에서 굵게로 변환
+          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/^##+ (.+)/*\1*/')
+
+          # 마크다운 URL을 Slack 포맷 URL로 변환
+          CHANGELOG=$(echo "$CHANGELOG" | sed -E 's/\\?([[][^]]+]\\?)\\?[(]([^()]+)\\?[)]/<\2|\1>/g')
+
+          # 수정된 변경로그를 환경 파일에 작성
+          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
+          echo "$CHANGELOG" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+      - name: Get current package version
+        id: package-version
+        uses: martinbeentjes/npm-get-version-action@v1.2.3
+        with:
+          path: packages/my-components
+
+      - name: Send to Slack via Webhook
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          CHANGELOG_CONTENT: ${{ env.CHANGELOG_CONTENT }}
+        run: |
+          # JSON 구문 오류를 방지하기 위해 변경로그 내용의 이중 따옴표를 이스케이프
+          ESCAPED_CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | sed 's/\^H//g' | sed 's/"/\\"/g')
+
+          # 결합된 메시지를 Slack으로 전송
+          curl -X POST --data-urlencode "payload={
+            \"username\": \"release-bot\",
+            \"blocks\": [
+              {
+                \"type\": \"header\",
+                \"text\": {
+                  \"type\": \"plain_text\",
+                  \"text\": \"${{ steps.package-version.outputs.current-version }} 릴리즈 열차가 출발합니다 🚂\",
+                  \"emoji\": true
+                }
+              },
+              {
+                \"type\": \"section\",
+                \"text\": {
+                  \"type\": \"mrkdwn\",
+                  \"text\": \"Vapor ${{ steps.package-version.outputs.current-version }} 버전의 *릴리즈 노트* 를 작성해주세요 \n이번 스프린트에 릴리즈할 *피그마 링크를 댓글에 달아주세요*\"
+                }
+              },
+              {
+                \"type\": \"divider\"
+              },
+              {
+                \"type\": \"section\",
+                \"text\": {
+                  \"type\": \"mrkdwn\",
+                  \"text\": \"<https://github.com/ellen-lee-goorm/gds-onboarding/tree/release/${{env.RELEASE_BRANCH_NAME}}|release/${{env.RELEASE_BRANCH_NAME}}>\"
+                }
+              },
+              {
+                \"type\": \"section\",
+                \"text\": {
+                  \"type\": \"mrkdwn\",
+                  \"text\": \"${ESCAPED_CHANGELOG_CONTENT}\"
+                }
+              },
+              {
+                \"type\": \"section\",
+                \"text\": {
+                  \"type\": \"mrkdwn\",
+                  \"text\": \"> 릴리즈 항목을 모두 확인했다면, 완료 버튼을 눌러주세요\"
+                }
+              },
+              {
+                \"type\": \"actions\",
+                \"elements\": [
+                  {
+                    \"type\": \"button\",
+                    \"text\": {
+                      \"type\": \"plain_text\",
+                      \"text\": \"완료\",
+                      \"emoji\": true
+                    },
+                    \"value\": \"complete_release\",
+                    \"action_id\": \"complete_write_release_note\"
+                  }
+                ]
+              }
+            ]
+          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
+
+  release-finish:
+    runs-on: ubuntu-latest
+    # 봇에서 repository_dispatch 받았을 때
+    if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.clicked}}
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # 브랜치 최신화
       - name: Update remote branches
         run: git remote update
 
@@ -34,166 +198,24 @@ jobs:
           git checkout master
           git pull origin master
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '18.20.0'
-
-      - name: Install dependencies
-        run: yarn install
-
       - name: Install git flow
         run: |
           sudo apt-get update
           sudo apt-get install -y git-flow
 
-      - name: Get today's date
-        id: get_date
+      - name: Get Release branch's name
         run: |
-          echo "today_date=$(node -e 'const today = new Date(); console.log(`${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, "0")}${String(today.getDate()).padStart(2, "0")}`)')" >> $GITHUB_ENV
+          TODAY_DATE=$(node -e 'const today = new Date(); console.log(`${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, "0")}${String(today.getDate()).padStart(2, "0")}`)')
+          echo "RELEASE_BRANCH_NAME=${TODAY_DATE}-0" >> $GITHUB_ENV
 
-      - name: Start Release with git flow
+      - name: Set Git user info
         run: |
-          echo "Today date is: ${{ env.today_date }}"
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+
+      # 릴리즈 브랜치 닫기
+      - name: Publish Release Branch
+        run: |
           git flow init -d
-          echo "Done: git flow init"
-          git flow release start ${{ env.today_date }}
-          echo "Done: git flow release start"
-          git flow release publish ${{ env.today_date }}
-          echo "Done: git flow release publish"
-          yarn version --yes
-          echo "Done: yarn version"
-
-      - name: Commit and push CHANGELOG.md
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add CHANGELOG.md
-          git commit -m "chore: update CHANGELOG.md"
-          git push origin release/${{ github.ref_name }}
-
-  slack-alarm:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Send Slack Message
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          channel-id: ${{ secrets.TEST_CHANNEL_ID }}
-          payload: |
-            {
-              "text": "release message",
-              "blocks": [
-                {
-                  "type": "header",
-                  "text": {
-                    "type": "plain_text",
-                    "text": "${{github.event.inputs.sprint_number}} 스프린트 릴리즈 열차가 출발합니다 🚂",
-                    "emoji": true
-                  }
-                },
-                {
-                  "type": "section",
-                  "text": {
-                    "type": "mrkdwn",
-                    "text": "브랜치: <https://github.com/ellen-lee-goorm/gds-onboarding/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
-                  }
-                },
-                {
-                  "type": "divider"
-                },
-                {
-                  "type": "rich_text",
-                  "elements": [
-                    {
-                      "type": "rich_text_section",
-                      "elements": [
-                        {
-                          "type": "text",
-                          "text": "${{github.event.inputs.sprint_number}} 스프린트에는 ...",
-                          "style": {
-                            "bold": true
-                          }
-                        },
-                        {
-                          "type": "text",
-                          "text": "\n\n"
-                        }
-                      ]
-                    },
-                    {
-                      "type": "rich_text_list",
-                      "style": "bullet",
-                      "indent": 0,
-                      "border": 0,
-                      "elements": [
-                        {
-                          "type": "rich_text_section",
-                          "elements": [
-                            {
-                              "type": "text",
-                              "text": "업데이트1"
-                            }
-                          ]
-                        },
-                        {
-                          "type": "rich_text_section",
-                          "elements": [
-                            {
-                              "type": "text",
-                              "text": "업데이트1"
-                            }
-                          ]
-                        },
-                        {
-                          "type": "rich_text_section",
-                          "elements": [
-                            {
-                              "type": "text",
-                              "text": "업데이트1"
-                            }
-                          ]
-                        },
-                        {
-                          "type": "rich_text_section",
-                          "elements": [
-                            {
-                              "type": "text",
-                              "text": "업데이트1"
-                            }
-                          ]
-                        }
-                      ]
-                    }
-                  ]
-                },
-                {
-                  "type": "actions",
-                  "elements": [
-                    {
-                      "type": "button",
-                      "text": {
-                        "type": "plain_text",
-                        "emoji": true,
-                        "text": "승인"
-                      },
-                      "style": "primary",
-                      "value": "accept release"
-                    },
-                    {
-                      "type": "button",
-                      "text": {
-                        "type": "plain_text",
-                        "emoji": true,
-                        "text": "거절"
-                      },
-                      "style": "danger",
-                      "value": "reject release"
-                    }
-                  ]
-                }
-              ]
-            }
-
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
+          git checkout release/${{ env.RELEASE_BRANCH_NAME }}
+          git flow release finish -Fpn ${{ env.RELEASE_BRANCH_NAME }}
